### ISSUE TITLE
BKMoneyKit is breaking in iOS 10

### ISSUE THREAD

**Issue by ZeeshanKiyani** [bkook/BKMoneyKit#28]
The code is breaking when you pop or dismiss the view controller which has bkmoneykit textfields. Can you please fix this asap?

**Comment by Rodolfocartas** [comment]
I can confirm the error in the wild. This is what I see.

![screen shot 2016-09-27 at 11 16 45 pm](https://cloud.githubusercontent.com/assets/537091/18900594/a88aaee4-8508-11e6-86ce-6b46e41ecc3c.png)

**Comment by ZeeshanKiyani** [comment]
Well I found a temporary fix that is before calling pop or dismiss view controller we have to set bkmoneykit textfields delegates to nil. Then it won't break

**Comment by tomaskraina** [comment]
The issue is that `BKForwardingTextField` use `assign` type for `id<UITextFieldDelegate> userDelegate` property, which is not auto-zeroing:

```
@property (nonatomic, assign, readonly) id<UITextFieldDelegate> userDelegate;
```

Using `weak` instead of `assign` solves this issue:

```
@property (nonatomic, weak, readonly) id<UITextFieldDelegate> userDelegate;
```

**Comment by tomaskraina** [comment]
I see that @bkook has published 0.0.9 with this fix in it :) https://github.com/bkook/BKMoneyKit/commit/4da0f24cc2adc31f7e7d5e5bf8a38666c36c8e09

**Comment by bkook** [comment]
@tomaskraina Oh. You noticed that so fast! lol
I just fixed and I pushed to the cocoapods repo.

@ZeeshanKiyani 
Please check latest version. Thanks.

**Comment by tomaskraina** [comment]
You were quicker than me forking this and preparing a PR :)

**Comment by bkook** [comment]
@tomaskraina Thank you for your interest and sorry for late update.
