### ISSUE TITLE
BKCurrencyTextField formats

### ISSUE THREAD

**Issue by KanybekMomukeyev** [bkook/BKMoneyKit#29]
Hi, how we can change BKCurrencyTextField formats, for ex: 44.333 like this one, or enable only integer types: 44,000 ?

**Comment by bkook** [comment]
You can change format with numberFormatter property in BKCurrencyTextField. 

For details, please refer to NSNumberFormatter class.

Thank you. 
1. 10. 7. 오후 1:20 Kanybek notifications@github.com 작성:
