### ISSUE TITLE
0.0.9 version doesn't compile when cocoapods is used

### ISSUE THREAD

**Issue by YuriyNovikov** [bkook/BKMoneyKit#30]
I added BKMokeyKit with help cocoapods. And when I try compile my project I have error: 

BKMoneyKit/BKForwardingTextField.m:15:1: Cannot synthesize weak property because the current deployment target does not support weak references

If I change Deployment Target in BKMoneyKit my project will compile.

Cocoapods version is 1.1.0

**Comment by bkook** [comment]
What Xcode version do you use? And what's projects minimum OS target version?

나의 iPhone에서 보냄
1. 10. 20. 오후 8:05 YuriyNovikov notifications@github.com 작성:

**Comment by YuriyNovikov** [comment]
@bkook 
I use Xcode 8.0.
Minimum OS target version 8.0.

![image](https://cloud.githubusercontent.com/assets/4475970/19567171/e4f7ab00-96fd-11e6-8ab8-920c4d7a0e95.png)

**Comment by bkook** [comment]
In your screenshot, iOS Deployment Target is 4.3.
Can you try changing it 5.0 or above?

**Comment by YuriyNovikov** [comment]
@bkook  I can change but this file was generated by cocoapods. I think you have to add ios.deployment_target in your podspec file.

**Comment by mcany** [comment]
+1

**Comment by bkook** [comment]
@YuriyNovikov @mcany 
Sorry for late. I fixed as you said just now. Please check version 0.0.10.
