### ISSUE TITLE
There is an issue when setting the card number programatically it doesn't update the card logo

### ISSUE THREAD

**Issue by miguelef** [bkook/BKMoneyKit#32]
If i set the card number programatically it doesn't update the card logo. It only updates when you set the card number via writing it directly from keyboard.

The following case does NOT work:

`self.cardNumberField.text = numberOfCard`

It updates the text in the field but it does NOT update the card logo, how can I do to make the card logo load in this case where I set the card number programatically ?

**Comment by bkook** [comment]
Please use below property to set card number properly.

```
/**
 * The card number without blank space. (e.g., 1234123412341234)
 * Use this property to set or get card number instead of text property.
 */
@property (nonatomic, strong) NSString *cardNumber;
```

**Comment by miguelef** [comment]
Thanks!
