### ISSUE TITLE
Add compatibility with new Mastercard range

### ISSUE THREAD

**Issue by karlcod531** [bkook/BKMoneyKit#35]
Mastercard is releasing new cards that use BINs ranging from 222100-272099. Currently, this does not work with the current card patterns.
Source:
https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html
https://www.realexpayments.com/blog/mastercard-to-introduce-new-card-numbers/

**Comment by bkook** [comment]
I just updated `CardPatterns.plist` for new MasterCard pattern.
Please check newest version (0.0.11)
Thank you for reporting!

![new_master_card](https://cloud.githubusercontent.com/assets/984192/24874432/97938a8e-1e5f-11e7-8956-d758068f9cfe.png)

**Comment by karlcod531** [comment]
Thank you for doing this! Just one question, did you do it based on the range I have given you above or do you know of a different range? because according to your pattern 272100 works, but it is not in the range above. Is the range I have given above incorrect? Thanks

**Comment by karlcod531** [comment]
I have confirmed through the MasterCard website that the range I have given is the correct one. However, using your code the BIN 270xxx does not work although it should because it is in the given range. Could you change it? Thanks

**Comment by bkook** [comment]
Sorry. There was some mistake to the card pattern.
I just fixed it and please update to `0.0.12`. If you have problem feel free to leave comments.
Thanks.

**Comment by MeGaPk** [comment]
maybe close this ticket, because problem resolved :)?
